export default {
  SUITS: ["♠", "♥", "♦", "♣"],
  RANKS: [
    { value: "A", rank: 1 },
    { value: "2", rank: 2 },
    { value: "3", rank: 3 },
    { value: "4", rank: 4 },
    { value: "5", rank: 5 },
    { value: "6", rank: 6 },
    { value: "7", rank: 7 },
    { value: "8", rank: 8 },
    { value: "9", rank: 9 },
    { value: "10", rank: 10 },
    { value: "J", rank: 11 },
    { value: "Q", rank: 12 },
    { value: "K", rank: 13 },
  ],
  DEFAULT_SETTINGS : {
    drawCount: 3,
    scoring: {
      wasteToTableau: 10,
      wasteToFoundation: 15,
      tableauToTableau: 5,
      tableauToFoundation: 30,
      foundationToTableau: -30,
    },
    countUndoRedo: true,
    timedGame: true,
    vegasScoring: true,
    soundEffects:false,
  },
  THEMES : {
    classic: {
      name: "Classic Green",
      background: "from-green-700 via-green-800 to-green-900",
      cardBack: "from-blue-600 to-blue-800",
      cardBackBorder: "border-blue-900",
      foundation: "bg-green-800 border-green-700",
      foundationHover: "bg-green-600 border-green-400",
      emptyPileBorder: "border-green-600",
      stockPile: "from-green-800 to-green-900 border-green-600",
      statsBar: "bg-green-900",
    },
    ocean: {
      name: "Ocean Blue",
      background: "from-blue-700 via-blue-800 to-blue-900",
      cardBack: "from-cyan-600 to-cyan-800",
      cardBackBorder: "border-cyan-900",
      foundation: "bg-blue-800 border-blue-700",
      foundationHover: "bg-blue-600 border-blue-400",
      emptyPileBorder: "border-blue-600",
      stockPile: "from-blue-800 to-blue-900 border-blue-600",
      statsBar: "bg-blue-900",
    },
    sunset: {
      name: "Sunset Pink",
      background: "from-pink-700 via-purple-800 to-pink-900",
      cardBack: "from-rose-600 to-rose-800",
      cardBackBorder: "border-rose-900",
      foundation: "bg-purple-800 border-purple-700",
      foundationHover: "bg-purple-600 border-purple-400",
      emptyPileBorder: "border-pink-600",
      stockPile: "from-purple-800 to-purple-900 border-purple-600",
      statsBar: "bg-purple-900",
    },
    royal: {
      name: "Royal Purple",
      background: "from-purple-700 via-indigo-800 to-purple-900",
      cardBack: "from-indigo-600 to-indigo-800",
      cardBackBorder: "border-indigo-900",
      foundation: "bg-indigo-800 border-indigo-700",
      foundationHover: "bg-indigo-600 border-indigo-400",
      emptyPileBorder: "border-purple-600",
      stockPile: "from-indigo-800 to-indigo-900 border-indigo-600",
      statsBar: "bg-indigo-900",
    },
    forest: {
      name: "Forest Dark",
      background: "from-emerald-800 via-teal-900 to-emerald-950",
      cardBack: "from-teal-700 to-teal-900",
      cardBackBorder: "border-teal-950",
      foundation: "bg-emerald-900 border-emerald-800",
      foundationHover: "bg-emerald-700 border-emerald-500",
      emptyPileBorder: "border-emerald-700",
      stockPile: "from-emerald-900 to-teal-950 border-emerald-700",
      statsBar: "bg-emerald-950",
    },
  }
};
